# Generated by Django 4.0.5 on 2022-09-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telnumber',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='persnumber',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
