# Generated by Django 4.0.5 on 2022-08-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Т', 'Телефон'), ('Ч', 'Часы'), ('Н', 'Наушники')], max_length=50)),
                ('vendor', models.CharField(max_length=10)),
                ('availability', models.CharField(choices=[('Д', 'Доступен в наличии'), ('П', 'Предзаказ')], max_length=50)),
                ('characteristics', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Qwe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qwe', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
