# Generated by Django 4.0.5 on 2022-08-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qwe',
        ),
    ]
