# Generated by Django 4.0.5 on 2022-08-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0003_alter_product_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
