# Generated by Django 4.0.5 on 2022-08-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0004_aadfa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aadfa',
        ),
    ]
