# Generated by Django 4.0.5 on 2022-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0006_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Т', 'Телефон'), ('Ч', 'Часы'), ('Н', 'Наушники')], max_length=50)),
                ('vendor', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('availability', models.CharField(choices=[('Д', 'Доступен в наличии'), ('П', 'Предзаказ')], max_length=50)),
                ('characteristics', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
