# Generated by Django 4.0.5 on 2022-08-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0007_products_delete_product_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
