# Generated by Django 4.0.5 on 2022-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0009_rename_vendor_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
