# Generated by Django 4.0.5 on 2022-08-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0010_alter_products_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
