# Generated by Django 4.0.5 on 2022-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0012_alter_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, choices=[('Доступен в наличии', 'Доступен в наличии'), ('Предзаказ', 'Предзаказ')], default='', max_length=50),
        ),
    ]
