# Generated by Django 4.0.5 on 2022-09-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopMTS', '0016_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
